

export const CART_PRODUCT_REQUEST = 'CART_PRODUCT_REQUEST';
export const CART_PRODUCT_SUCCESS = 'CART_PRODUCT_SUCCESS';
export const CART_PRODUCT_FAILED = 'CART_PRODUCT_FAILED';

export const PRODUCT_ADD_CART_REQUEST = 'PRODUCT_ADD_CART_REQUEST';
export const PRODUCT_REMOVE_FROM_CART = 'PRODUCT_REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const INCREMENT_PRODUCT_QUANTITY = 'INCREMENT_PRODUCT_QUANTITY';
export const DECREMENT_PRODUCT_QUANTITY = 'DECREMENT_PRODUCT_QUANTITY';

export const WISHLIST_PRODUCT_REQUEST = 'WISHLIST_PRODUCT_REQUEST';
export const WISHLIST_PRODUCT_SUCCESS = 'WISHLIST_PRODUCT_SUCCESS';
export const WISHLIST_PRODUCT_FAILED = 'WISHLIST_PRODUCT_FAILED';
export const WISHLIST_ADD_REQUEST = 'WISHLIST_ADD_REQUEST';
export const WISHLIST_REMOVE_REQUEST = 'WISHLIST_REMOVE_REQUEST';
